---
title: "MA677 hw4"
author: "Yinfeng Zhou"
date: "2021/3/14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load("tidyverse","magrittr")
```

## Fiji earthquakes
```{r}
options(digits=2, scipen=999)

fiji<-read.csv("fijiquakes.csv",sep="")
fijicdf<-ecdf(fiji$mag)
nfiji<-nrow(fiji)
alpha=.05
X<-seq(0,max(fiji$mag),length=1000)
fx<-fijicdf(X)
epsilon<-sqrt((1/(2*nfiji))*log(2/alpha))
L<-pmax(fx-epsilon,0)
U<-pmin(fx+epsilon,1)

plot.ecdf(fijicdf,pch=20)
lines(X,L,type="l",lty=1,col="red")
lines(X,U,type="l",lty=1,col="red")

E<-fijicdf(4.9)-fijicdf(4.3)
varfiji<-function(x){
  vf<-(fijicdf(x)*(1-fijicdf(x)))/nfiji
  return(vf)
}
v<-varfiji(4.9)+varfiji(4.3)
sd<-sqrt(v)
cl<-round(E-2*sd,2)
cr<-round(E+2*sd,2)
paste("Confidence interval at .05 is [",cl,",",cr,"]")
```

## Old faithful
```{r,eval=FALSE}
faith<-read.table("faithful.dat",sep="\t",skip=20,header=TRUE)

faith%<>%separate(eruptions.waiting,c("index","eruptions","waiting"),sep="\\s+")
write.csv(faith,"faithful.csv",col.names = TRUE)


faithcdf<-ecdf(faith$waiting)
X_f<-seq(0,max(faith$waiting),length=1000)
fx_f<-faithcdf(X_f)
mean_f<-mean(fx_f)
var_f<-var(fx_f)
se_f<-sqrt(var_f)
fl<-round(mean_f-se_f,2)
fr<-round(mean_f+se_f,2)
paste("Confidence interval at .1 is [",fl,",",fr,"]")
paste("Mean is",round(mean_f,2),", standard error is",round(se_f,2),", median is",round(median(fx_f),2))
```

## KS problem
```{r}
set.seed(1)
x_sim<-rep(0,10000)
y_sim<-rep(0,10000)

for(i in 1:5000)
{
  x_sim[i]=runif(1,0,1/2)
  y_sim[i]=runif(1,0,3/4)
  while(y_sim[i]>3/2*x_sim[i]){
    x_sim[i]=runif(1,0,1/2)
    y_sim[i]=runif(1,0,3/4)
  }
}
for(i in 5000:10000)
{
  x_sim[i]=runif(1,1/2,1)
  y_sim[i]=runif(1,3/4,1)
  while(y_sim[i]>1/2*(x_sim[i]+1)){
    x_sim[i]=runif(1,1/2,1)
    y_sim[i]=runif(1,3/4,1)
  }
}
plot(x_sim,y_sim)
ks_1<-c(0.42,0.06,0.88,0.40,0.90,0.38,0.78,0.71,0.57,0.66,0.48,0.35,0.16,0.22,0.08,0.11,0.29,0.79,0.75,0.82,0.30,0.23,0.01,0.41,0.09)
ks.test(ks_1,x_sim)
```


```{r,eval=FALSE,include=FALSE}
cdf_real<-function(x){
  if(x>0&&x<1){
  y<-ifelse(x > 1/2, 1/2 * (x+1), 3/2 * x)
  }else {y=0}
  return(y)
}
ks.test(ks_1,"cdf_real")
```

